apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
data:
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_HOST: "coworking-prj-postgresql"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: env-secret
type: Opaque
stringData:
  DB_PASSWORD: "dGhlIHBhc3N3b3Jk"
  